# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SpotifyTui < Formula
  desc "Brutalist terminal UI for Spotify on macOS"
  homepage "https://github.com/Wondr-design/spotify"
  version "0.2.6"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/Wondr-design/spotify/releases/download/v0.2.6/spotify-tui_darwin_amd64.tar.gz"
    sha256 "3e8e3cdbc715c26b2a899f833b0bd9d07785984162005bec116872a92fbbb642"

    def install
      bin.install "spotify-tui"
      bin.install_symlink "spotify-tui" => "spot"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/Wondr-design/spotify/releases/download/v0.2.6/spotify-tui_darwin_arm64.tar.gz"
    sha256 "be22f014fbcd71d62de7da335c6dc0e20c54aa3ebadf85960787324166c0dbee"

    def install
      bin.install "spotify-tui"
      bin.install_symlink "spotify-tui" => "spot"
    end
  end

  test do
    system "#{bin}/spot", "--version"
  end
end
