# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SpotifyTui < Formula
  desc "Brutalist terminal UI for Spotify on macOS"
  homepage "https://github.com/Wondr-design/spotify"
  version "0.2.0"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/Wondr-design/spotify/releases/download/v0.2.0/spotify-tui_darwin_amd64.tar.gz"
    sha256 "238953fb2354129fddafee4462ba26725977339d7e7525ecebc900eafb559e35"

    def install
      bin.install "spotify-tui"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/Wondr-design/spotify/releases/download/v0.2.0/spotify-tui_darwin_arm64.tar.gz"
    sha256 "b47257597b3fc86f3f8f4c2ff7f1a9e67a41ab4c2693846e45f822471a4a721f"

    def install
      bin.install "spotify-tui"
    end
  end

  test do
    system "#{bin}/spotify-tui", "--version"
  end
end
